---

version: "3"

services:
  mpe:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "19132:19132/udp"
    volumes:
      - ./worlds:/app/worlds
      - ./server.properties:/app/server.properties
